### ISSUE TITLE
show span tag

### ISSUE THREAD

**Issue by mmiat** [TravisSpangle/redmine_spent_time_in_issue_description#30]
Hi
I don't use very much time and this plugin, so I don't know from when I've this problem, but I've noticed it only today. in the Hours' column il show "Other" for some rows, and the entire span tag for others:

<pre><span class="translation_missing" title="translation missing: it.plugin_spent_time_in_issue.datetime.minutes.other">Other</span></pre>

**Comment by TravisSpangle** [comment]
Please run the rake about command and post the results http://guides.rubyonrails.org/command_line.html#about

If you could include a screen shot and HTML source that would be helpful.

**Comment by mmiat** [comment]
thanks

![screenshot 2015-09-06 18 46 03](https://cloud.githubusercontent.com/assets/11910225/9705543/c0df3de2-54c7-11e5-875c-13bd2275f653.png)

**Comment by mmiat** [comment]
I don't know rake about command, I launch it in redmine root and I've:

<pre>rake aborted!
ActiveRecord::AdapterNotSpecified: database configuration does not specify adapter
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:47:in `resolve_hash_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:41:in `resolve_string_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:25:in `spec'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/railtie.rb:88:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `each'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => about => environment
(See full trace by running task with --trace)</pre>

**Comment by TravisSpangle** [comment]
You will have to include RAILS_ENV=production on the rake command.

what language is your application running in? Looks like it's having trouble defaulting to English or choking on the translation values.

**Comment by mmiat** [comment]
my application is in italian, but I've not problem until some days ago. however, your question gives me an idea: I copied en.yml as it.yml and now it's ok. I think you only need to use en.yml when language is different and not present in locales
thanks

**Comment by TravisSpangle** [comment]
That is good news. If you want to provide an Italian translation I will add it to the project.

Keeping this open for now. The plugin should default to english when the current language isn't provided.
