### ISSUE TITLE
undefined method `render_custom_fields_rows'

### ISSUE THREAD

**Issue by ikodev** [TravisSpangle/redmine_spent_time_in_issue_description#41]
Hi !
I just installed the plugin and got now 500 errors when opening issues on redmine.
Here is my config :
```
Environment:
  Redmine version                3.3.2.devel
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
Redmine plugins:
  redmine_spent_time             3.1.2
  redmine_spent_time_in_issue_description 2.8.0
  redmine_work_time              0.3.4
  time_logger                    0.5.4
```

The error : 
```
Started GET "/issues/10" for 127.0.0.1 at 2017-03-13 09:58:49 +0100
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"10"}
  Current user: guillaume (id=5)
  Rendered issues/_action_menu.html.erb (4.4ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb within layouts/base (39.9ms)
Completed 500 Internal Server Error in 236ms (ActiveRecord: 17.5ms)

ActionView::Template::Error (undefined method `render_custom_fields_rows' for #<#<Class:0x0000000542a608>:0x00000005414e70>):
    68:     end
    69:   end
    70: end %>
    71: <%= render_custom_fields_rows(@issue) %>
    72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    73: </div>
    74: 
  plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb:71:in `_plugins_redmine_spent_time_in_issue_description_app_views_issues_show_html_erb__1438118927607099876_44059060'
  app/controllers/issues_controller.rb:116:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:109:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Thank you for your advices !

Guillaume

**Comment by lbayerlein** [comment]
I installed it on my server, too. There is the same error as @ikodev described.
