### ISSUE TITLE
open issue contain subtask , occur 500 error

### ISSUE THREAD

**Issue by archonwang** [TravisSpangle/redmine_spent_time_in_issue_description#42]
@TravisSpangle , @nicolnx , 

my environment is 
```
Environment:
  Redmine version                3.3.3.stable.16543
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

when I open an issue contain subtask, it occured 500 error.
please check it . Thanks.

```
Started GET "/issue_badge/issues_count" for 192.168.20.231 at 2017-04-23 13:21:24 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: hui.wang (id=8)
  Rendered text template (0.0ms)
Completed 200 OK in 12ms (Views: 0.4ms | ActiveRecord: 3.8ms)
Started GET "/issue_badge/issues_count" for 192.168.20.231 at 2017-04-23 13:21:28 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: hui.wang (id=8)
  Rendered text template (0.0ms)
Completed 200 OK in 13ms (Views: 0.4ms | ActiveRecord: 3.9ms)
Started GET "/issues/3446" for 192.168.20.231 at 2017-04-23 13:21:34 +0800
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"3446"}
  Current user: hui.wang (id=8)
STATEMENT 
STATEMENT projects.id = 2 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_blocked_reason/app/views/blocked_reason/_blocked_reason_button.html.erb (1.3ms)
  Rendered plugins/redmine_blocked_reason/app/views/issues/_action_menu.html.erb (9.4ms)
  Rendered plugins/advanced_roadmap_v2/app/views/hooks/issues/_show.html.erb (43.0ms)
  Rendered plugins/redmine_assignee_selector/app/views/issues/_assignee_selector.html.erb (10.9ms)
  Rendered plugins/redmine_close_button/app/views/issues/_close_button.html.erb (0.5ms)
  Rendered plugins/redmine_show_issue_assignee_avatar/app/views/hooks/_view_issues_show_details_bottom.erb (1.5ms)
  Rendered plugins/redmine_blocked_reason/app/views/blocked_reason/_blocked_reason_window.html.erb (3.1ms)
  Rendered plugins/redmine_issue_checklist/app/views/issues/_checklist.html.erb (2.0ms)
  Rendered plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb (2949.2ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb within layouts/base (3074.1ms)
Completed 500 Internal Server Error in 3236ms (ActiveRecord: 75.4ms)

ActionView::Template::Error (undefined method `render_issue_self_and_descendants_tree' for #<#<Class:0x000000086fbf50>:0x00000008f11780>):
    3: <div id="issue_tree">
    4:   <% @issue.ancestors.visible.all.each do |i| %>
    5:     <% if i.root? %>
    6:       <%= render_issue_self_and_descendants_tree(i, @issue) %>
    7:     <% end %>
    8:   <% end %>
    9: </div>
  plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb:6:in `block in _3b4f7e961eaf07c22d242cd67622fc3e'
  plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb:4:in `_3b4f7e961eaf07c22d242cd67622fc3e'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb:92:in `_894dd5990954928fad694d83fc0b8425'
  plugins/redmine_spent_time_in_issue_description/lib/issues_controller_patch.rb:36:in `block (2 levels) in show_with_plugin'
  plugins/redmine_spent_time_in_issue_description/lib/issues_controller_patch.rb:33:in `show_with_plugin'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/issues/3446" for 192.168.20.231 at 2017-04-23 13:21:38 +0800
Processing by IssuesController#show as */*
  Parameters: {"id"=>"3446"}
  Current user: hui.wang (id=8)
STATEMENT 
STATEMENT projects.id = 2 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_blocked_reason/app/views/blocked_reason/_blocked_reason_button.html.erb (1.4ms)
  Rendered plugins/redmine_blocked_reason/app/views/issues/_action_menu.html.erb (9.5ms)
  Rendered plugins/advanced_roadmap_v2/app/views/hooks/issues/_show.html.erb (41.4ms)
  Rendered plugins/redmine_assignee_selector/app/views/issues/_assignee_selector.html.erb (10.6ms)
  Rendered plugins/redmine_close_button/app/views/issues/_close_button.html.erb (0.5ms)
  Rendered plugins/redmine_show_issue_assignee_avatar/app/views/hooks/_view_issues_show_details_bottom.erb (1.5ms)
  Rendered plugins/redmine_blocked_reason/app/views/blocked_reason/_blocked_reason_window.html.erb (3.1ms)
  Rendered plugins/redmine_issue_checklist/app/views/issues/_checklist.html.erb (2.0ms)
  Rendered plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb (3233.0ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb within layouts/base (3354.5ms)
Completed 500 Internal Server Error in 3518ms (ActiveRecord: 74.0ms)

ActionView::Template::Error (undefined method `render_issue_self_and_descendants_tree' for #<#<Class:0x000000086fbf50>:0x007f9700f236d8>):
    3: <div id="issue_tree">
    4:   <% @issue.ancestors.visible.all.each do |i| %>
    5:     <% if i.root? %>
    6:       <%= render_issue_self_and_descendants_tree(i, @issue) %>
    7:     <% end %>
    8:   <% end %>
    9: </div>
  plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb:6:in `block in _3b4f7e961eaf07c22d242cd67622fc3e'
  plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb:4:in `_3b4f7e961eaf07c22d242cd67622fc3e'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb:92:in `_894dd5990954928fad694d83fc0b8425'
  plugins/redmine_spent_time_in_issue_description/lib/issues_controller_patch.rb:36:in `block (2 levels) in show_with_plugin'
  plugins/redmine_spent_time_in_issue_description/lib/issues_controller_patch.rb:33:in `show_with_plugin'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/issue_badge/issues_count" for 192.168.20.231 at 2017-04-23 13:21:55 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: hui.wang (id=8)
  Rendered text template (0.0ms)
Completed 200 OK in 13ms (Views: 0.6ms | ActiveRecord: 4.0ms)
Started GET "/issue_badge/issues_count" for 192.168.20.231 at 2017-04-23 13:21:57 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: hui.wang (id=8)
  Rendered text template (0.0ms)
Completed 200 OK in 19ms (Views: 0.4ms | ActiveRecord: 10.4ms)

```

**Comment by archonwang** [comment]
it seems that the plugin is conflict with redmine_show_parent_at_subtask(https://github.com/minoru-nagasawa/redmine_show_parent_at_subtask)
