### ISSUE TITLE
Crash with redmine 3.4.0

### ISSUE THREAD

**Issue by ludovicandrieux** [TravisSpangle/redmine_spent_time_in_issue_description#46]
Hi,

When you see an issue with your plugin in a vanilla redmine 3.4.0, you get an error 500.
Here the stack :

> Started GET "/redmine/issues/1" for 195.101.153.198 at 2017-07-04 16:41:28 +0200
> Processing by IssuesController#show as HTML
>   Parameters: {"id"=>"1"}
>   Current user: test (id=1)
>   Rendered issues/_action_menu.html.erb (8.2ms)
>   Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb within layouts/base (92.1ms)
> Completed 500 Internal Server Error in 215ms (ActiveRecord: 30.8ms)
> 
> ActionView::Template::Error (undefined method `render_custom_fields_rows' for #<#<Class:0x0000000a9a4ea8>:0x00000007e42968>):
>     68:     end
>     69:   end
>     70: end %>
>     71: <%= render_custom_fields_rows(@issue) %>
>     72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
>     73: </div>
>     74:
>   plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb:71:in `_plugins_redmine_spent_time_in_issue_description_app_views_issues_show_html_erb__1857580760139882178_88995140'
>   app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
>   app/controllers/issues_controller.rb:99:in `show'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Best regards
Ludovic

**Comment by ghost** [comment]
The Following patch to the show.html that is overwritten by this plugin resolves this issue.

--- 3.4.0.show.html.erb	2017-12-20 13:06:48.917832685 +0100
+++ 3.2.0.show.html.erb	2017-12-20 12:58:39.394558857 +0100
@@ -68,7 +68,7 @@
     end
   end
 end %>
-<%= render_half_width_custom_fields_rows(@issue) %>
+<%= render_custom_fields_rows(@issue) %>
 <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
 </div>
 
@@ -173,4 +173,4 @@
     <%= auto_discovery_link_tag(:atom, {:format => 'atom', :key => User.current.rss_key}, :title => "#{@issue.project} - #{@issue.tracker} ##{@issue.id}: #{@issue.subject}") %>
 <% end %>
 
-<%= context_menu %>
+<%= context_menu issues_context_menu_path %>

**Comment by Pierstoval** [comment]
@rtwo Can you submit this patch to the repo so it can be merged? I just upgraded an am facing this issue

**Comment by Huangzc88** [comment]
![image](https://user-images.githubusercontent.com/31158857/50054171-52e6b500-017a-11e9-8da6-95e69595d5a4.png)

There's this problem in 3.4.7.
